const api = async (url, options = {}) => { const response = await fetch(url, { credentials: "same-origin", ...options }); let data = null; try { data = await response.json(); } catch {} return { response, data }; };
const params = new URLSearchParams(location.search);
const esc = (value) => String(value ?? "").replace(/[&<>\"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;" }[c]));
const access = document.querySelector("#trip-access");
const summary = document.querySelector("#trip-summary");
const itemsOutput = document.querySelector("#trip-items");
const inviteMessage = document.querySelector("#invite-message");
function render(data, readOnly) { const trip = data.trip; document.title = `${trip.title} | RegReady Hunt`; document.querySelector("#trip-title").textContent = trip.title; access.textContent = readOnly ? "Shared read-only" : "Owner workspace"; summary.innerHTML = `<div class="summary-stat"><b>${esc(trip.species)}</b><span>species</span></div><div class="summary-stat"><b>${esc(trip.state)}</b><span>state</span></div><div class="summary-stat"><b>${esc(trip.start_date)} → ${esc(trip.end_date)}</b><span>hunt window</span></div><div class="summary-stat"><b>${esc(trip.region || "Open")}</b><span>region</span></div>`; itemsOutput.innerHTML = (data.items || []).map((item) => `<article class="record-card"><div><span class="record-kind">${esc(item.kind)}</span><h3>${esc(item.title)}</h3><p>${esc(item.notes || "")}</p>${item.source_url ? `<a href="${esc(item.source_url)}" target="_blank" rel="noreferrer">Open source ↗</a>` : ""}</div><span class="item-status">${esc(item.status)}</span></article>`).join(""); if (readOnly) document.querySelector("#invite-form").closest(".account-card").innerHTML = `<h3>Read-only crew link</h3><p class="muted">This shared view is safe to send to your buddies. The owner can create member access later.</p>`; }
async function load() { if (params.get("share")) { const result = await api(`/api/trips/share/${encodeURIComponent(params.get("share"))}`); if (!result.response.ok) { document.querySelector("#trip-title").textContent = "Shared trip not found"; return; } render(result.data, true); return; } const id = params.get("id"); if (!id) { document.querySelector("#trip-title").textContent = "Choose a trip from the workspace"; return; } const result = await api(`/api/trips/${encodeURIComponent(id)}`); if (!result.response.ok) { document.querySelector("#trip-title").textContent = "Sign in or choose a valid trip"; return; } render(result.data, false); document.querySelector("#invite-form").addEventListener("submit", async (event) => { event.preventDefault(); const form = event.currentTarget; const invite = await api(`/api/trips/${encodeURIComponent(id)}/invite`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ displayName: form.querySelector("#invite-name").value, email: form.querySelector("#invite-email").value }) }); inviteMessage.textContent = invite.response.ok ? `Share link: ${location.origin}${invite.data.shareUrl}` : (invite.data?.error || "Could not create link."); }); }
load();
